// Product and Category Data for Ink Matrix

export interface Product {
  id: string;
  sku?: string;
  name: string;
  description: string;
  keyComponents?: string;
  materials?: string;
  specifications?: string;
  designFeatures?: string;
  price: number;
  originalPrice?: number;
  image: string;
  additionalImages?: string[];
  category: string;
  subcategory: string;
  bulkPricing: { minQty: number; price: number }[];
  customizable: boolean;
  colors?: string[];
  inStock: boolean;
  stock?: number;
  rating: number;
  reviews: number;
  badge?: 'bestseller' | 'new' | 'sale';
}

export interface Category {
  id: string;
  name: string;
  image: string;
  subcategories: string[];
}

export const categories: Category[] = [
  {
    id: 'gift-sets',
    name: 'Gift Sets',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=400&q=80',
    subcategories: ['2-in-1 Sets', '3-in-1 Sets', '4-in-1 Sets', '5-in-1 Sets', '6-in-1 Sets', '7-in-1 Sets'],
  },
  {
    id: 'pens',
    name: 'Pens',
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&q=80',
    subcategories: ['Metal Ball Pens', 'Bamboo Pens', 'Stylus Pens', 'Rollerball Pens', 'Executive Pens'],
  },
  {
    id: 'mugs',
    name: 'Mugs & Tumblers',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&q=80',
    subcategories: ['Travel Mugs', 'Insulated Mugs', 'Ceramic Mugs', 'Tumblers', 'Self-Stirring Mugs'],
  },
  {
    id: 'water-bottles',
    name: 'Water Bottles',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80',
    subcategories: ['Stainless Steel', 'Vacuum Insulated', 'Bamboo Lid', 'Sports Bottles', 'Glass Bottles'],
  },
  {
    id: 'electronics',
    name: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80',
    subcategories: ['Power Banks', 'Speakers', 'Earbuds', 'Wireless Chargers', 'Digital Clocks'],
  },
  {
    id: 'keychains',
    name: 'Keychains',
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=400&q=80',
    subcategories: ['Metal Keychains', 'Bamboo Keychains', 'Leather Keychains', 'Multi-function Keychains'],
  },
  {
    id: 'desktop-organizers',
    name: 'Desktop Organizers',
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&q=80',
    subcategories: ['Pen Holders', 'Desk Clocks', 'Wooden Organizers', 'Multi-function Organizers'],
  },
  {
    id: 'notebooks',
    name: 'Notebooks & Diaries',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&q=80',
    subcategories: ['A5 Notebooks', 'Executive Diaries', 'Cork Notebooks', 'Bamboo Notebooks'],
  },
  {
    id: 'accessories',
    name: 'Accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
    subcategories: ['Badge Holders', 'Card Holders', 'Lanyards', 'Travel Kits'],
  },
];

export const products: Product[] = [
  // Gift Sets
  {
    id: 'XG-001',
    sku: 'XG-001',
    name: '3-in-1 Gift Set - Brown & Black',
    description: 'Premium gift set featuring Brown Kit, Black Kit, and Designer Bag. Multi-use packaging perfect for corporate gifting.',
    keyComponents: 'Brown Kit, Black Kit, Designer Bag',
    materials: 'Brown, Black',
    specifications: 'Includes bag + kits',
    designFeatures: 'Multi-use, premium packaging',
    price: 1499,
    originalPrice: 1899,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '3-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1399 },
      { minQty: 50, price: 1299 },
      { minQty: 100, price: 1199 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 500,
    rating: 4.8,
    reviews: 234,
    badge: 'bestseller',
  },
  {
    id: 'XG-GS-246',
    sku: 'XG-GS-246',
    name: '4-in-1 Premium Gift Set',
    description: 'Complete desk set featuring Borosilicate glass bottle (600ml), glass mug (500ml), vegan leather diary, and metal pen.',
    keyComponents: 'Borosilicate glass bottle, Borosilicate glass mug, Vegan leather diary, Metal pen',
    materials: 'Glass, Vegan Leather, Metal',
    specifications: 'Bottle: 600ml, Mug: 500ml, Complete desk set',
    designFeatures: 'Eco-friendly, elegant, functional',
    price: 2499,
    originalPrice: 2999,
    image: 'https://images.unsplash.com/photo-1513001900722-370f803f498d?w=600&q=80',
    category: 'gift-sets',
    subcategory: '4-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 2299 },
      { minQty: 50, price: 2099 },
      { minQty: 100, price: 1899 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#8B4513'],
    inStock: true,
    stock: 300,
    rating: 4.9,
    reviews: 156,
    badge: 'new',
  },
  {
    id: 'XG-015',
    sku: 'XG-015',
    name: '5-in-1 Gift Set - Multi Color',
    description: 'Bold multi-kit bundle featuring White, Red, and Black kits. Complete set ideal for team gifting.',
    keyComponents: 'White Kit, Red Kit, Black Kit',
    materials: 'White, Red, Black',
    specifications: 'Multi-kit bundle',
    designFeatures: 'Bold color mix, complete set',
    price: 2999,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '5-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 2799 },
      { minQty: 50, price: 2599 },
      { minQty: 100, price: 2399 },
    ],
    customizable: true,
    colors: ['#ffffff', '#dc2626', '#2d2d2d'],
    inStock: true,
    stock: 200,
    rating: 4.7,
    reviews: 89,
  },

  // Pens
  {
    id: 'XG-MP-01',
    sku: 'XG-MP-01',
    name: 'Aluminum Metal Ball Pen',
    description: 'Sleek aluminum body metal ball pen with signature design. Perfect for professional branding.',
    keyComponents: 'Metal ball pen with signature design',
    materials: 'Aluminum',
    specifications: '13.2 × 1.1 cm',
    designFeatures: 'Sleek aluminum body, professional look',
    price: 149,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Metal Ball Pens',
    bulkPricing: [
      { minQty: 50, price: 129 },
      { minQty: 100, price: 109 },
      { minQty: 250, price: 89 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#ffffff', '#dc2626', '#4a5568'],
    inStock: true,
    stock: 1000,
    rating: 4.6,
    reviews: 412,
    badge: 'bestseller',
  },
  {
    id: 'XG-MP-02',
    sku: 'XG-MP-02',
    name: 'Bamboo Grip Ball Pen',
    description: 'Eco stylus ball pen with natural bamboo grip. Features integrated stylus tip for touchscreens.',
    keyComponents: 'Eco stylus ball pen with bamboo grip',
    materials: 'Bamboo, Metal',
    specifications: '14.8 × 2 × 2 cm',
    designFeatures: 'Natural bamboo grip, integrated stylus tip',
    price: 179,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Bamboo Pens',
    bulkPricing: [
      { minQty: 50, price: 159 },
      { minQty: 100, price: 139 },
      { minQty: 250, price: 119 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#dc2626', '#2d2d2d'],
    inStock: true,
    stock: 800,
    rating: 4.5,
    reviews: 289,
  },
  {
    id: 'XG-MP-06',
    sku: 'XG-MP-06',
    name: 'Luxury Gold Accents Rollerball Pen',
    description: 'Premium glossy metal body with gold-plated clip. Twist-off cap with smooth rollerball writing experience.',
    keyComponents: 'Premium glossy metal body with gold-plated clip',
    materials: 'Metal, Gold Plating',
    specifications: '14 × 1.2 × 1.2 cm',
    designFeatures: 'Twist-off cap, smooth rollerball writing',
    price: 399,
    originalPrice: 499,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Executive Pens',
    bulkPricing: [
      { minQty: 25, price: 369 },
      { minQty: 50, price: 339 },
      { minQty: 100, price: 299 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f'],
    inStock: true,
    stock: 400,
    rating: 4.9,
    reviews: 198,
    badge: 'new',
  },

  // Mugs
  {
    id: 'XG-M01',
    sku: 'XG-M01',
    name: 'Double-Walled Insulated Travel Mug',
    description: 'Stainless steel travel mug with handle and spill-proof lid. Perfect for on-the-go professionals.',
    keyComponents: 'Stainless steel travel mug with handle and spill-proof lid',
    materials: 'Stainless Steel',
    specifications: '350 ml, 105 mm height, 85 mm diameter',
    designFeatures: 'Insulated, leak-proof, travel-ready',
    price: 599,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Travel Mugs',
    bulkPricing: [
      { minQty: 25, price: 549 },
      { minQty: 50, price: 499 },
      { minQty: 100, price: 449 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#2d2d2d', '#ffffff', '#dc2626'],
    inStock: true,
    stock: 600,
    rating: 4.7,
    reviews: 345,
    badge: 'bestseller',
  },
  {
    id: 'XG-M04',
    sku: 'XG-M04',
    name: 'Eco-Friendly Bamboo & Stainless Steel Mug',
    description: 'Bamboo and stainless steel insulated mug with wooden handle. Sustainable materials for eco-conscious brands.',
    keyComponents: 'Bamboo and stainless steel insulated mug with wooden handle',
    materials: 'Bamboo, Stainless Steel',
    specifications: '350 ml, 110 mm height, 80 mm diameter',
    designFeatures: 'Sustainable materials, wooden handle',
    price: 749,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Insulated Mugs',
    bulkPricing: [
      { minQty: 25, price: 699 },
      { minQty: 50, price: 649 },
      { minQty: 100, price: 599 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 450,
    rating: 4.8,
    reviews: 178,
  },
  {
    id: 'XG-M12',
    sku: 'XG-M12',
    name: '304 Stainless Steel Self-Stirring Coffee Mug',
    description: 'Self-stirring mug with handle and silicone cup lid. Built-in stirrer for perfect mixing every time.',
    keyComponents: 'Self-stirring mug with handle and silicone cup lid',
    materials: '304 Stainless Steel, Silicone',
    specifications: '400 ml, 120 mm height, 90 mm diameter',
    designFeatures: 'Built-in stirrer, food-grade stainless steel',
    price: 899,
    originalPrice: 1099,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Self-Stirring Mugs',
    bulkPricing: [
      { minQty: 25, price: 849 },
      { minQty: 50, price: 799 },
      { minQty: 100, price: 749 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 300,
    rating: 4.6,
    reviews: 234,
    badge: 'new',
  },

  // Water Bottles
  {
    id: 'XG-002',
    sku: 'XG-002',
    name: 'Vacuum-Insulated 304 Stainless Steel Bottle',
    description: 'Premium vacuum insulated bottle with secure cap and wrist strap. Stylish design for professionals.',
    keyComponents: 'Secure cap and wrist strap',
    materials: '304 Stainless Steel',
    specifications: '750 ml, 22 cm height, 6.6 cm diameter',
    designFeatures: 'Stylish, insulated, secure strap',
    price: 699,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Vacuum Insulated',
    bulkPricing: [
      { minQty: 25, price: 649 },
      { minQty: 50, price: 599 },
      { minQty: 100, price: 549 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#2d2d2d', '#ffffff', '#dc2626'],
    inStock: true,
    stock: 700,
    rating: 4.8,
    reviews: 456,
    badge: 'bestseller',
  },
  {
    id: 'XG-020',
    sku: 'XG-020',
    name: '304 Stainless Steel Bottle with Bamboo Lid',
    description: 'Eco-friendly insulated bottle with beautiful bamboo lid and carry handle.',
    keyComponents: 'Bamboo lid and carry handle',
    materials: '304 Stainless Steel, Bamboo',
    specifications: '750 ml, 26.5 cm height, 7.8 cm diameter',
    designFeatures: 'Eco-friendly bamboo lid',
    price: 849,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Bamboo Lid',
    bulkPricing: [
      { minQty: 25, price: 799 },
      { minQty: 50, price: 749 },
      { minQty: 100, price: 699 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 500,
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 'XG-065',
    sku: 'XG-065',
    name: 'Smart Bamboo Vacuum Flask with LED Temperature Display',
    description: 'Smart vacuum flask with LED temperature display. Eco bamboo finish with high-tech functionality.',
    keyComponents: 'LED temperature display',
    materials: 'Bamboo, 304 Stainless Steel',
    specifications: '500 ml, 23.5 cm height, 7 cm diameter',
    designFeatures: 'Smart display, eco bamboo',
    price: 1299,
    originalPrice: 1599,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Stainless Steel',
    bulkPricing: [
      { minQty: 25, price: 1199 },
      { minQty: 50, price: 1099 },
      { minQty: 100, price: 999 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 250,
    rating: 4.9,
    reviews: 167,
    badge: 'new',
  },

  // Electronics
  {
    id: 'XG-T01',
    sku: 'XG-T01',
    name: '10000mAh Power Bank with LED Display',
    description: 'Compact power bank with LED battery indicator. Dual USB ports and Type-C input for fast charging.',
    keyComponents: 'LED battery indicator, Dual USB ports',
    materials: 'ABS Plastic, Lithium Battery',
    specifications: '10000mAh, Type-C input',
    designFeatures: 'Compact, fast charging, dual ports',
    price: 999,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80',
    category: 'electronics',
    subcategory: 'Power Banks',
    bulkPricing: [
      { minQty: 25, price: 899 },
      { minQty: 50, price: 799 },
      { minQty: 100, price: 699 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#ffffff', '#1e3a5f'],
    inStock: true,
    stock: 400,
    rating: 4.6,
    reviews: 312,
    badge: 'bestseller',
  },
  {
    id: 'XG-T11',
    sku: 'XG-T11',
    name: 'Fusion Multi-Function Wireless Sound Box',
    description: 'Bluetooth speaker with clock, phone stand, and pen holder. All-in-one desk accessory.',
    keyComponents: 'Bluetooth speaker, Clock, Phone stand, Pen holder',
    materials: 'ABS Plastic, Metal',
    specifications: 'Bluetooth v5.3, 5W speaker, 1200mAh battery, 4-8hr play',
    designFeatures: 'Telescopic phone holder, Pen stand, Alarm, Temperature display',
    price: 1499,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    category: 'electronics',
    subcategory: 'Speakers',
    bulkPricing: [
      { minQty: 25, price: 1399 },
      { minQty: 50, price: 1299 },
      { minQty: 100, price: 1199 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#ffffff'],
    inStock: true,
    stock: 300,
    rating: 4.7,
    reviews: 198,
    badge: 'new',
  },
  {
    id: 'XG-T62',
    sku: 'XG-T62',
    name: 'Wireless Sport Earphone',
    description: 'Wireless over-ear sports earphones with up to 16hrs playtime. Cool lighting and protein leather ear muffs.',
    keyComponents: 'Wireless over-ear sports earphones',
    materials: 'Protein Leather, ABS Plastic',
    specifications: 'Up to 16hrs playtime, CVC microphone',
    designFeatures: 'Cool lighting, Protein leather ear muffs, Folding design, Ergonomic',
    price: 1799,
    originalPrice: 2199,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80',
    category: 'electronics',
    subcategory: 'Earbuds',
    bulkPricing: [
      { minQty: 25, price: 1699 },
      { minQty: 50, price: 1599 },
      { minQty: 100, price: 1499 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 350,
    rating: 4.5,
    reviews: 145,
    badge: 'sale',
  },

  // Keychains
  {
    id: 'XG-K1',
    sku: 'XG-K1',
    name: 'Circular Shaped Keychain',
    description: 'Circular stainless steel keychain with matt and ghost finish sides. Perfect for engraving or print branding.',
    keyComponents: 'Circular stainless steel keychain',
    materials: 'Stainless Steel',
    specifications: 'Matt & Ghost finish sides',
    designFeatures: 'Engraving / Print branding, pp Packing',
    price: 99,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Metal Keychains',
    bulkPricing: [
      { minQty: 50, price: 89 },
      { minQty: 100, price: 79 },
      { minQty: 250, price: 69 },
    ],
    customizable: true,
    colors: ['#c0c0c0', '#2d2d2d'],
    inStock: true,
    stock: 2000,
    rating: 4.4,
    reviews: 567,
  },
  {
    id: 'XG-K20',
    sku: 'K-20',
    name: 'Bamboo With Stainless Steel Keychain',
    description: 'Eco-friendly bamboo and stainless steel keychain. Natural bamboo finish with UV Print, Laser & Screen branding.',
    keyComponents: 'Bamboo and steel keychain',
    materials: 'Bamboo, Stainless Steel',
    specifications: 'Natural Bamboo color',
    designFeatures: 'UV Print, Laser & Screen branding',
    price: 129,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Bamboo Keychains',
    bulkPricing: [
      { minQty: 50, price: 119 },
      { minQty: 100, price: 109 },
      { minQty: 250, price: 99 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 1500,
    rating: 4.6,
    reviews: 234,
    badge: 'new',
  },
  {
    id: 'XG-K36',
    sku: 'XG-K36',
    name: 'Modern Metal & Leather Hook Keychain',
    description: 'Keychain with metal hook and leather strap. Modern aesthetic with versatile attachment.',
    keyComponents: 'Keychain with metal hook and leather strap',
    materials: 'Metal, Faux Leather',
    specifications: 'Rectangular metal top, black faux leather strap',
    designFeatures: 'Modern aesthetic, versatile attachment',
    price: 179,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Leather Keychains',
    bulkPricing: [
      { minQty: 50, price: 169 },
      { minQty: 100, price: 159 },
      { minQty: 250, price: 149 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513'],
    inStock: true,
    stock: 1000,
    rating: 4.5,
    reviews: 178,
  },

  // Desktop Organizers
  {
    id: 'XG-D01',
    sku: 'XG-D01',
    name: 'Desk Table Clock Organizer',
    description: 'Desk organizer with clock, pen holder, mobile slot, and calendar. Customizable name plate included.',
    keyComponents: 'Clock, pen holder, mobile slot, calendar',
    materials: 'Wanka Rattan',
    specifications: 'Removable clock',
    designFeatures: 'Customizable name plate',
    price: 799,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Wooden Organizers',
    bulkPricing: [
      { minQty: 25, price: 749 },
      { minQty: 50, price: 699 },
      { minQty: 100, price: 649 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 400,
    rating: 4.7,
    reviews: 234,
    badge: 'bestseller',
  },
  {
    id: 'XG-D03',
    sku: 'XG-D03',
    name: 'Wooden Desk Organizer with Clock & Mobile Holder',
    description: 'Premium beech wood organizer with folding watch, pen & phone holder. Built-in analog clock with customizable name engraving.',
    keyComponents: 'Wooden organizer with folding watch, pen & phone holder',
    materials: 'Solid Beech Wood',
    specifications: 'Dimensions: 18.8x6.7x10 cm',
    designFeatures: 'Built-in analog clock, Removable clock, Customizable name engraving',
    price: 999,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Desk Clocks',
    bulkPricing: [
      { minQty: 25, price: 949 },
      { minQty: 50, price: 899 },
      { minQty: 100, price: 849 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 300,
    rating: 4.8,
    reviews: 167,
  },
  {
    id: 'XG-T64',
    sku: 'XG-T64',
    name: 'Bamboo Pen Clock',
    description: 'Eco-friendly bamboo digital clock with pen holder. Displays time, date, temp with 3 alarms and clap & tap control.',
    keyComponents: 'Digital clock with pen holder functions',
    materials: 'Eco-friendly Bamboo',
    specifications: 'Runs on AAA batteries or USB, Dimensions: 19x10x6.5cm',
    designFeatures: 'Displays time, date, temp, 3 alarms, Clap & tap control',
    price: 699,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Pen Holders',
    bulkPricing: [
      { minQty: 25, price: 649 },
      { minQty: 50, price: 599 },
      { minQty: 100, price: 549 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 350,
    rating: 4.6,
    reviews: 145,
    badge: 'new',
  },

  // Notebooks
  {
    id: 'XG-NB01',
    sku: 'XG-NB01',
    name: 'A5 Notebook Diary with Magnetic Buckle',
    description: 'Executive notebook with magnetic buckle and pen holder. Premium PU vegan leather with 200 pages.',
    keyComponents: 'Executive notebook with magnetic buckle & pen holder',
    materials: 'PU Vegan Leather',
    specifications: '148x210mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Magnetic clasp, Penholder, Hardcover',
    price: 449,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'A5 Notebooks',
    bulkPricing: [
      { minQty: 50, price: 399 },
      { minQty: 100, price: 349 },
      { minQty: 250, price: 299 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513', '#1e3a5f'],
    inStock: true,
    stock: 800,
    rating: 4.9,
    reviews: 456,
    badge: 'bestseller',
  },
  {
    id: 'XG-NB29',
    sku: 'XG-NB29',
    name: 'Cork & PU Leather Notebook',
    description: 'Eco-friendly cork and PU leather notebook with elastic band. Sustainable material for eco-conscious brands.',
    keyComponents: 'Cork & PU leather notebook with elastic band',
    materials: 'Cork PU Leather',
    specifications: '148x212mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Elastic strap, Cork + Leather (Hardcover)',
    price: 549,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'Cork Notebooks',
    bulkPricing: [
      { minQty: 50, price: 499 },
      { minQty: 100, price: 449 },
      { minQty: 250, price: 399 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 600,
    rating: 4.7,
    reviews: 234,
    badge: 'new',
  },
  {
    id: 'XG-NB28',
    sku: 'XG-NB28',
    name: 'Woodgrain Bamboo Hardcover Notebook',
    description: 'Beautiful woodgrain hardcover notebook with bamboo cover. Natural aesthetic for eco-friendly branding.',
    keyComponents: 'Woodgrain hardcover notebook',
    materials: 'PU Bamboo',
    specifications: '148x212mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Bookmark, Bamboo cover (Hardcover)',
    price: 599,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'Bamboo Notebooks',
    bulkPricing: [
      { minQty: 50, price: 549 },
      { minQty: 100, price: 499 },
      { minQty: 250, price: 449 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 500,
    rating: 4.8,
    reviews: 189,
  },

  // Accessories
  {
    id: 'XG-Y09',
    sku: 'XG-Y09',
    name: 'Oval Shaped Retractable Loop Badge Holder',
    description: 'Professional retractable badge holder with oval shape and loop design. Secure and durable for daily use.',
    keyComponents: 'Retractable loop, oval shape',
    materials: 'Plastic, Metal',
    specifications: 'Height: 2.54 in (65 mm), Width: 0.34 in (10 mm)',
    designFeatures: 'Retractable, secure, professional',
    price: 79,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'accessories',
    subcategory: 'Badge Holders',
    bulkPricing: [
      { minQty: 50, price: 69 },
      { minQty: 100, price: 59 },
      { minQty: 250, price: 49 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#dc2626'],
    inStock: true,
    stock: 3000,
    rating: 4.3,
    reviews: 567,
  },
  {
    id: 'XG-GS-254',
    sku: 'XG-GS-254',
    name: '3-in-1 Leather Card Holder Set',
    description: 'Premium brown leather card holder with keychain and metal pen. Multi-function keychain with bottle opener and loop.',
    keyComponents: 'Leather card holder, Keychain, Metal pen',
    materials: 'Brown Leather, Metal',
    specifications: 'Compact gift set',
    designFeatures: 'Multi-function keychain (bottle opener, loop)',
    price: 699,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'accessories',
    subcategory: 'Card Holders',
    bulkPricing: [
      { minQty: 25, price: 649 },
      { minQty: 50, price: 599 },
      { minQty: 100, price: 549 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d', '#ffffff'],
    inStock: true,
    stock: 400,
    rating: 4.6,
    reviews: 234,
  },
];

export const businessNeeds = [
  {
    id: 'startups',
    title: 'For Startups',
    description: 'Budget-friendly branded merchandise',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&q=80',
  },
  {
    id: 'corporate',
    title: 'Corporate Gifts',
    description: 'Premium gifts for clients & partners',
    image: 'https://images.unsplash.com/photo-1513001900722-370f803f498d?w=400&q=80',
  },
  {
    id: 'events',
    title: 'Event Merchandise',
    description: 'Branded swag for conferences & events',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&q=80',
  },
  {
    id: 'employee',
    title: 'Employee Kits',
    description: 'Welcome kits & appreciation gifts',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&q=80',
  },
];
