// Product and Category Data for Ink Matrix

export interface Product {
  id: string;
  sku?: string;
  name: string;
  description: string;
  keyComponents?: string;
  materials?: string;
  specifications?: string;
  designFeatures?: string;
  price: number;
  originalPrice?: number;
  image: string;
  additionalImages?: string[];
  category: string;
  subcategory: string;
  bulkPricing: { minQty: number; price: number }[];
  customizable: boolean;
  colors?: string[];
  inStock: boolean;
  stock?: number;
  rating: number;
  reviews: number;
  badge?: 'bestseller' | 'new' | 'sale';
}

export interface Category {
  id: string;
  name: string;
  image: string;
  subcategories: string[];
}

export const categories: Category[] = [
  {
    id: 'gift-sets',
    name: 'Gift Sets',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=400&q=80',
    subcategories: ['2-in-1 Sets', '3-in-1 Sets', '4-in-1 Sets', '5-in-1 Sets', '6-in-1 Sets', '7-in-1 Sets'],
  },
  {
    id: 'pens',
    name: 'Pens',
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&q=80',
    subcategories: ['Metal Ball Pens', 'Bamboo Pens', 'Stylus Pens', 'Rollerball Pens', 'Executive Pens'],
  },
  {
    id: 'mugs',
    name: 'Mugs & Tumblers',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&q=80',
    subcategories: ['Travel Mugs', 'Insulated Mugs', 'Eco Mugs', 'Tumblers', 'Self-Stirring Mugs'],
  },
  {
    id: 'water-bottles',
    name: 'Water Bottles',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80',
    subcategories: ['Stainless Steel', 'Vacuum Insulated', 'Bamboo Lid', 'Sports Bottles', 'Aluminum Bottles'],
  },
  {
    id: 'electronics',
    name: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80',
    subcategories: ['Power Banks', 'Speakers', 'Earbuds', 'Wireless Chargers', 'Digital Clocks'],
  },
  {
    id: 'keychains',
    name: 'Keychains',
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=400&q=80',
    subcategories: ['Metal Keychains', 'Bamboo Keychains', 'Leather Keychains', 'Multi-function Keychains', 'Wooden Keychains'],
  },
  {
    id: 'desktop-organizers',
    name: 'Desktop Organizers',
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&q=80',
    subcategories: ['Pen Holders', 'Desk Clocks', 'Wooden Organizers', 'Multi-function Organizers', 'MDF Organizers'],
  },
  {
    id: 'notebooks',
    name: 'Notebooks & Diaries',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&q=80',
    subcategories: ['A5 Notebooks', 'Executive Diaries', 'Cork Notebooks', 'Bamboo Notebooks', 'Magnetic Closure'],
  },
  {
    id: 'accessories',
    name: 'Accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80',
    subcategories: ['Badge Holders', 'Card Holders', 'Lanyards', 'Travel Kits'],
  },
];

export const products: Product[] = [
  // =================== GIFT SETS ===================
  {
    id: 'XG-008',
    sku: 'XG-008',
    name: '4-in-1 Gift Set - Wooden Kit',
    description: 'Premium wooden kit with designer bag. Multi-use packaging perfect for corporate gifting.',
    keyComponents: 'Wooden Kit, Designer Bag',
    materials: 'Premium Wood',
    specifications: 'Complete 4-in-1 set with designer bag',
    designFeatures: 'Multi-use, premium packaging',
    price: 1899,
    originalPrice: 2299,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '4-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1799 },
      { minQty: 50, price: 1699 },
      { minQty: 100, price: 1599 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 500,
    rating: 4.8,
    reviews: 234,
    badge: 'bestseller',
  },
  {
    id: 'XG-011',
    sku: 'XG-011',
    name: '4-in-1 Gift Set - White Kit',
    description: 'Elegant white kit with designer bag. Clean aesthetic for premium gifting.',
    keyComponents: 'White Kit, Designer Bag',
    materials: 'Premium Materials',
    specifications: 'Complete 4-in-1 set',
    designFeatures: 'Elegant white design',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '4-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1799 },
      { minQty: 50, price: 1699 },
      { minQty: 100, price: 1599 },
    ],
    customizable: true,
    colors: ['#ffffff', '#2d2d2d'],
    inStock: true,
    stock: 400,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 'XG-012',
    sku: 'XG-012',
    name: '4-in-1 Gift Set - Gray Kit',
    description: 'Sophisticated gray kit with designer bag. Professional look for corporate events.',
    keyComponents: 'Gray Kit, Designer Bag',
    materials: 'Premium Materials',
    specifications: 'Complete 4-in-1 set',
    designFeatures: 'Sophisticated gray design',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '4-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1799 },
      { minQty: 50, price: 1699 },
      { minQty: 100, price: 1599 },
    ],
    customizable: true,
    colors: ['#6b7280', '#2d2d2d'],
    inStock: true,
    stock: 350,
    rating: 4.6,
    reviews: 156,
  },
  {
    id: 'XG-016',
    sku: 'XG-016',
    name: '5-in-1 Gift Set - Gray & Black Kit',
    description: 'Complete 5-in-1 set with gray and black options. Ideal for team gifting.',
    keyComponents: 'Gray Kit, Black Kit',
    materials: 'Premium Materials',
    specifications: 'Complete 5-in-1 set',
    designFeatures: 'Dual color options',
    price: 2499,
    originalPrice: 2999,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '5-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 2399 },
      { minQty: 50, price: 2299 },
      { minQty: 100, price: 2199 },
    ],
    customizable: true,
    colors: ['#6b7280', '#2d2d2d'],
    inStock: true,
    stock: 300,
    rating: 4.8,
    reviews: 212,
    badge: 'new',
  },
  {
    id: 'XG-024',
    sku: 'XG-024',
    name: '5-in-1 Gift Set - Premium',
    description: 'Premium 5-in-1 gift set with complete desk accessories.',
    keyComponents: 'Complete desk set',
    materials: 'Premium Materials',
    specifications: 'Complete 5-in-1 set',
    designFeatures: 'Premium quality',
    price: 2699,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '5-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 2599 },
      { minQty: 50, price: 2499 },
      { minQty: 100, price: 2399 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f'],
    inStock: true,
    stock: 250,
    rating: 4.9,
    reviews: 178,
  },
  {
    id: 'XG-026',
    sku: 'XG-026',
    name: '5-in-1 Gift Set - Wooden Kit Box',
    description: 'Premium wooden kit with box packing. Elegant gifting solution.',
    keyComponents: 'Wooden Kit, Box Packing',
    materials: 'Premium Wood',
    specifications: 'Complete 5-in-1 set with box',
    designFeatures: 'Premium wooden finish',
    price: 2899,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '5-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 2799 },
      { minQty: 50, price: 2699 },
      { minQty: 100, price: 2599 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 200,
    rating: 4.9,
    reviews: 145,
    badge: 'bestseller',
  },
  {
    id: 'XG-039',
    sku: 'XG-039',
    name: '7-in-1 Gift Set - Premium Collection',
    description: 'Complete 7-in-1 gift set with top view, inside view, and designer bag. Ultimate corporate gifting solution.',
    keyComponents: 'Top View, Inside View, Designer Bag',
    materials: 'Premium Materials',
    specifications: 'Complete 7-in-1 set, Dimensions: 25x50x15x30',
    designFeatures: 'Ultimate premium collection',
    price: 3499,
    originalPrice: 3999,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '7-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 3299 },
      { minQty: 50, price: 3099 },
      { minQty: 100, price: 2899 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#8B4513'],
    inStock: true,
    stock: 150,
    rating: 4.9,
    reviews: 234,
    badge: 'new',
  },
  {
    id: 'XG-042',
    sku: 'XG-042',
    name: '7-in-1 Gift Set - Designer Collection',
    description: 'Designer 7-in-1 gift set with premium bag.',
    keyComponents: 'Top View, Inside View, Designer Bag',
    materials: 'Premium Materials',
    specifications: 'Complete 7-in-1 set',
    designFeatures: 'Designer collection',
    price: 3699,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '7-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 3499 },
      { minQty: 50, price: 3299 },
      { minQty: 100, price: 3099 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513'],
    inStock: true,
    stock: 120,
    rating: 4.8,
    reviews: 167,
  },
  {
    id: 'XG-GS-245',
    sku: 'XG-GS-245',
    name: '2-in-1 Gift Set - Mug & Umbrella',
    description: 'Premium insulated coffee mug with temperature display and solid case umbrella (UPF 50+).',
    keyComponents: 'Vacuum Travel Mug, Solid Case Umbrella',
    materials: 'Stainless Steel, UPF 50+ Fabric',
    specifications: 'Temperature display mug, compact umbrella',
    designFeatures: 'Compact, insulated, travel-ready',
    price: 1499,
    originalPrice: 1799,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '2-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1399 },
      { minQty: 50, price: 1299 },
      { minQty: 100, price: 1199 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 400,
    rating: 4.7,
    reviews: 189,
    badge: 'new',
  },
  {
    id: 'XG-GS-246',
    sku: 'XG-GS-246',
    name: '4-in-1 Premium Gift Set - Glass Collection',
    description: 'Complete desk set featuring Borosilicate glass bottle (600ml), glass mug (500ml) with bamboo straw, vegan leather diary, and metal pen.',
    keyComponents: 'Borosilicate glass bottle, Glass mug with bamboo straw, Vegan leather diary, Metal pen',
    materials: 'Borosilicate Glass, Vegan Leather, Metal',
    specifications: 'Bottle: 600ml, Mug: 500ml with bamboo straw, A5 diary with magnetic strap',
    designFeatures: 'Eco-friendly, elegant, functional',
    price: 2499,
    originalPrice: 2999,
    image: 'https://images.unsplash.com/photo-1513001900722-370f803f498d?w=600&q=80',
    category: 'gift-sets',
    subcategory: '4-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 2299 },
      { minQty: 50, price: 2099 },
      { minQty: 100, price: 1899 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#8B4513'],
    inStock: true,
    stock: 300,
    rating: 4.9,
    reviews: 156,
    badge: 'bestseller',
  },
  {
    id: 'XG-GS-247',
    sku: 'XG-GS-247',
    name: '2-in-1 Gift Set - Bamboo Mug & Bottle',
    description: 'Eco-friendly bamboo mug (350ml) with leak-proof lid and black matte insulated bottle (500ml).',
    keyComponents: 'Bamboo mug, Black matte insulated bottle',
    materials: 'Bamboo, Stainless Steel',
    specifications: 'Mug: 350ml, Bottle: 500ml',
    designFeatures: 'Leak-proof bamboo lid with rope handle',
    price: 1599,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '2-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1499 },
      { minQty: 50, price: 1399 },
      { minQty: 100, price: 1299 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 350,
    rating: 4.6,
    reviews: 134,
  },
  {
    id: 'XG-GS-248',
    sku: 'XG-GS-248',
    name: '2-in-1 Gift Set - Bottle & Ceramic Mug',
    description: 'Vacuum insulated stainless steel bottle (500ml) keeps hot 10hrs/cold 30hrs. White ceramic-style mug (200ml) with spill-resistant lid.',
    keyComponents: 'Vacuum bottle, Ceramic-style mug, Rope keychain hook',
    materials: 'Stainless Steel, Ceramic-style',
    specifications: 'Bottle: 500ml, Mug: 200ml',
    designFeatures: 'Keeps hot 10hrs, cold 30hrs',
    price: 1699,
    originalPrice: 1999,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '2-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1599 },
      { minQty: 50, price: 1499 },
      { minQty: 100, price: 1399 },
    ],
    customizable: true,
    colors: ['#ffffff', '#2d2d2d'],
    inStock: true,
    stock: 280,
    rating: 4.7,
    reviews: 167,
  },
  {
    id: 'XG-GS-250',
    sku: 'XG-GS-250',
    name: '2-in-1 Gift Set - White & Black',
    description: 'Matte white vacuum insulated bottle (500ml) and glossy stainless steel travel mug (350ml) with ergonomic handle.',
    keyComponents: 'White bottle, Glossy travel mug',
    materials: 'Stainless Steel',
    specifications: 'Bottle: 500ml, Mug: 350ml',
    designFeatures: 'Modern black & white design, minimal aesthetic',
    price: 1799,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '2-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1699 },
      { minQty: 50, price: 1599 },
      { minQty: 100, price: 1499 },
    ],
    customizable: true,
    colors: ['#ffffff', '#2d2d2d'],
    inStock: true,
    stock: 320,
    rating: 4.8,
    reviews: 145,
    badge: 'new',
  },
  {
    id: 'XG-GS-251',
    sku: 'XG-GS-251',
    name: '2-in-1 Gift Set - Bamboo Lid Bottle & Cork Mug',
    description: 'Matte white insulated bottle (500ml) with bamboo lid and carry loop. White ceramic mug (350ml) with cork base and sip lid.',
    keyComponents: 'Bamboo lid bottle, Cork base mug',
    materials: 'Stainless Steel, Bamboo, Cork',
    specifications: 'Bottle: 500ml, Mug: 350ml',
    designFeatures: 'Eco-friendly, insulated, ergonomic',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    category: 'gift-sets',
    subcategory: '2-in-1 Sets',
    bulkPricing: [
      { minQty: 25, price: 1799 },
      { minQty: 50, price: 1699 },
      { minQty: 100, price: 1599 },
    ],
    customizable: true,
    colors: ['#ffffff', '#8B4513'],
    inStock: true,
    stock: 250,
    rating: 4.9,
    reviews: 189,
    badge: 'bestseller',
  },

  // =================== PENS ===================
  {
    id: 'XG-MP-01',
    sku: 'XG-MP-01',
    name: 'Aluminum Metal Ball Pen',
    description: 'Sleek aluminum body metal ball pen with signature design. Perfect for professional branding.',
    keyComponents: 'Metal ball pen with signature design',
    materials: 'Aluminum',
    specifications: '13.2 × 1.1 cm',
    designFeatures: 'Sleek aluminum body, professional look',
    price: 149,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Metal Ball Pens',
    bulkPricing: [
      { minQty: 50, price: 129 },
      { minQty: 100, price: 109 },
      { minQty: 250, price: 89 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#ffffff', '#dc2626', '#4a5568'],
    inStock: true,
    stock: 1000,
    rating: 4.6,
    reviews: 412,
    badge: 'bestseller',
  },
  {
    id: 'XG-MP-02',
    sku: 'XG-MP-02',
    name: 'Bamboo Grip Eco Stylus Ball Pen',
    description: 'Eco stylus ball pen with natural bamboo grip. Features integrated stylus tip for touchscreens.',
    keyComponents: 'Eco stylus ball pen with bamboo grip',
    materials: 'Bamboo, Metal',
    specifications: '14.8 × 2 × 2 cm',
    designFeatures: 'Natural bamboo grip, integrated stylus tip',
    price: 179,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Bamboo Pens',
    bulkPricing: [
      { minQty: 50, price: 159 },
      { minQty: 100, price: 139 },
      { minQty: 250, price: 119 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#dc2626', '#2d2d2d'],
    inStock: true,
    stock: 800,
    rating: 4.5,
    reviews: 289,
  },
  {
    id: 'XG-MP-05',
    sku: 'XG-MP-05',
    name: 'Multifunctional 2-in-1 Phone Stand Metal Ball Pen',
    description: 'Versatile metal ball pen with built-in phone stand. Sublimation printing compatible.',
    keyComponents: '2-in-1 phone stand and pen',
    materials: 'Metal',
    specifications: '14 × 2 × 2 cm',
    designFeatures: 'Flat angular tip, signature design, phone stand',
    price: 199,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Stylus Pens',
    bulkPricing: [
      { minQty: 50, price: 179 },
      { minQty: 100, price: 159 },
      { minQty: 250, price: 139 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#2d2d2d', '#dc2626'],
    inStock: true,
    stock: 700,
    rating: 4.4,
    reviews: 234,
    badge: 'new',
  },
  {
    id: 'XG-MP-07',
    sku: 'XG-MP-07',
    name: 'T-Shock Metallic Click Metal Ball Pen',
    description: 'Premium metallic ball pen with sleek finish in vibrant colors. Click mechanism for convenience.',
    keyComponents: 'Metallic click ball pen',
    materials: 'Metal',
    specifications: '15 × 10 × 3 cm',
    designFeatures: 'Sleek metallic body, vibrant finishes, signature design',
    price: 169,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Metal Ball Pens',
    bulkPricing: [
      { minQty: 50, price: 149 },
      { minQty: 100, price: 129 },
      { minQty: 250, price: 109 },
    ],
    customizable: true,
    colors: ['#22c55e', '#c0c0c0', '#dc2626', '#1e3a5f'],
    inStock: true,
    stock: 900,
    rating: 4.5,
    reviews: 312,
  },
  {
    id: 'XG-MP-12',
    sku: 'XG-MP-12',
    name: 'Indigo Metal Ball Pen',
    description: 'Premium matte black body with distinctive arrow-shaped clip. Fluid writing experience.',
    keyComponents: 'Premium matte black metal pen',
    materials: 'Metal',
    specifications: '14 × 3 × 3 cm',
    designFeatures: 'Arrow-shaped clip, sophisticated feel, fluid writing',
    price: 249,
    originalPrice: 299,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Executive Pens',
    bulkPricing: [
      { minQty: 50, price: 229 },
      { minQty: 100, price: 209 },
      { minQty: 250, price: 189 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#c0c0c0', '#B76E79', '#FFD700'],
    inStock: true,
    stock: 600,
    rating: 4.8,
    reviews: 278,
    badge: 'bestseller',
  },
  {
    id: 'XG-MP-22',
    sku: 'XG-MP-22',
    name: 'Vibrant Stylus Slim Metal Ball Pen',
    description: 'Dual function pen with vibrant colors. Smooth writing performance with stylus for touchscreens.',
    keyComponents: 'Slim metal ball pen with stylus tip',
    materials: 'Metal',
    specifications: '14 × 1.0 × 1.0 cm',
    designFeatures: 'Vibrant colors, dual function (writing + stylus), smooth performance',
    price: 159,
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=600&q=80',
    category: 'pens',
    subcategory: 'Stylus Pens',
    bulkPricing: [
      { minQty: 50, price: 139 },
      { minQty: 100, price: 119 },
      { minQty: 250, price: 99 },
    ],
    customizable: true,
    colors: ['#9f1239', '#2d2d2d', '#7c3aed', '#0ea5e9', '#1e3a5f'],
    inStock: true,
    stock: 1200,
    rating: 4.6,
    reviews: 345,
    badge: 'new',
  },

  // =================== MUGS & TUMBLERS ===================
  {
    id: 'XG-M01',
    sku: 'XG-M01',
    name: 'Double-Walled Insulated Travel Mug with Handle',
    description: 'Stainless steel travel mug with handle and spill-proof lid. Perfect for on-the-go professionals.',
    keyComponents: 'Stainless steel travel mug with handle and spill-proof lid',
    materials: 'Double-Walled Insulated Stainless Steel',
    specifications: '350 ml, 105 mm × 85 mm, 180g',
    designFeatures: 'Insulated, spill-proof lid, travel-ready',
    price: 599,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Travel Mugs',
    bulkPricing: [
      { minQty: 25, price: 549 },
      { minQty: 50, price: 499 },
      { minQty: 100, price: 449 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#2d2d2d', '#ffffff', '#dc2626'],
    inStock: true,
    stock: 600,
    rating: 4.7,
    reviews: 345,
    badge: 'bestseller',
  },
  {
    id: 'XG-M02',
    sku: 'XG-M02',
    name: 'Double-Walled Stainless Steel Travel Mug with Anti-Slip Base',
    description: 'Premium travel mug with handle and anti-slip base for stability.',
    keyComponents: 'Travel mug with anti-slip base',
    materials: 'Double-Walled Stainless Steel',
    specifications: '350 ml, 114 mm × 85 mm, 190g',
    designFeatures: 'Anti-slip base, comfortable handle',
    price: 649,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Travel Mugs',
    bulkPricing: [
      { minQty: 25, price: 599 },
      { minQty: 50, price: 549 },
      { minQty: 100, price: 499 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 500,
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 'XG-M03',
    sku: 'XG-M03',
    name: '304 Vacuum Insulated Mug with Transparent Lid',
    description: 'Double-walled vacuum insulated mug with transparent lid for visibility.',
    keyComponents: 'Vacuum insulated mug with transparent lid',
    materials: '304 Double-Walled Stainless Steel',
    specifications: '500 ml, 175 mm × 65 mm, 230g',
    designFeatures: 'Transparent lid, vacuum insulated',
    price: 749,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Insulated Mugs',
    bulkPricing: [
      { minQty: 25, price: 699 },
      { minQty: 50, price: 649 },
      { minQty: 100, price: 599 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#dc2626', '#ffffff'],
    inStock: true,
    stock: 450,
    rating: 4.7,
    reviews: 234,
  },
  {
    id: 'XG-M04',
    sku: 'XG-M04',
    name: 'Eco-Friendly Bamboo & Stainless Steel Insulated Mug',
    description: 'Bamboo and stainless steel insulated mug with wooden handle. Sustainable materials for eco-conscious brands.',
    keyComponents: 'Bamboo and stainless steel mug with wooden handle',
    materials: 'Bamboo, Stainless Steel',
    specifications: '350 ml, 110 mm × 80 mm, 220g',
    designFeatures: 'Sustainable materials, wooden handle, proof lid',
    price: 799,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Eco Mugs',
    bulkPricing: [
      { minQty: 25, price: 749 },
      { minQty: 50, price: 699 },
      { minQty: 100, price: 649 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 400,
    rating: 4.8,
    reviews: 198,
    badge: 'new',
  },
  {
    id: 'XG-M06',
    sku: 'XG-M06',
    name: 'Eco Bamboo & 304 Stainless Steel Travel Tumbler',
    description: 'Double-walled travel tumbler with handle and slide lid. Natural bamboo exterior.',
    keyComponents: 'Travel tumbler with bamboo exterior',
    materials: '304 Stainless Steel Interior, Natural Bamboo Exterior',
    specifications: '450 ml, 170 mm × 85 mm, 420g',
    designFeatures: 'Handle, slide lid, eco-friendly',
    price: 899,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Tumblers',
    bulkPricing: [
      { minQty: 25, price: 849 },
      { minQty: 50, price: 799 },
      { minQty: 100, price: 749 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 350,
    rating: 4.9,
    reviews: 167,
  },
  {
    id: 'XG-M08',
    sku: 'XG-M08',
    name: 'Wheat Fibre Eco-Friendly BPA-Free Mug',
    description: 'Sustainable wheat fibre mug with anti-bacterial properties. BPA-free and leak-proof.',
    keyComponents: 'Wheat fibre eco mug',
    materials: 'Wheat Fibre, BPA-Free Plastic',
    specifications: '450 ml, 140 mm × 80 mm, 150g',
    designFeatures: 'Sustainable, anti-bacterial, BPA-free, leak-proof',
    price: 449,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Eco Mugs',
    bulkPricing: [
      { minQty: 25, price: 399 },
      { minQty: 50, price: 349 },
      { minQty: 100, price: 299 },
    ],
    customizable: true,
    colors: ['#22c55e', '#1e3a5f', '#2d2d2d', '#f97316'],
    inStock: true,
    stock: 600,
    rating: 4.5,
    reviews: 234,
  },
  {
    id: 'XG-M12',
    sku: 'XG-M12',
    name: '304 Stainless Steel Self-Stirring Coffee Mug',
    description: 'Self-stirring mug with handle and silicone cup lid. Automatic magnetic stirring assembly.',
    keyComponents: 'Self-stirring mug with silicone lid',
    materials: '304 Stainless Steel Inside, PP Body Outside',
    specifications: '400 ml, Magnetic stirring assembly',
    designFeatures: 'Automatic stirring, food-grade stainless steel, silicone lid',
    price: 999,
    originalPrice: 1199,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Self-Stirring Mugs',
    bulkPricing: [
      { minQty: 25, price: 949 },
      { minQty: 50, price: 899 },
      { minQty: 100, price: 849 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 280,
    rating: 4.7,
    reviews: 189,
    badge: 'new',
  },
  {
    id: 'XG-M16',
    sku: 'XG-M16',
    name: 'Double-Wall Insulated Wine Tumbler',
    description: 'Vacuum insulated coffee wine mug. Keeps cold and hot for long time.',
    keyComponents: 'Vacuum insulated wine tumbler',
    materials: 'Double Wall 304 Stainless Steel',
    specifications: '400 ml, 300g',
    designFeatures: 'Double-wall vacuum insulation, keeps cold/hot long',
    price: 749,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Tumblers',
    bulkPricing: [
      { minQty: 25, price: 699 },
      { minQty: 50, price: 649 },
      { minQty: 100, price: 599 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#B76E79', '#FFD700'],
    inStock: true,
    stock: 400,
    rating: 4.6,
    reviews: 234,
    badge: 'bestseller',
  },
  {
    id: 'XG-M19',
    sku: 'XG-M19',
    name: 'Smart Temperature Display Coffee Mug',
    description: 'Premium coffee mug with digital temperature display and ergonomic handle.',
    keyComponents: 'Temperature display mug with ergonomic handle',
    materials: 'SUS 304 Stainless Steel Interior, BPA-Free Outer',
    specifications: '460 ml, 135 mm × 85 mm, 210g',
    designFeatures: 'Digital temperature display, ergonomic handle',
    price: 1099,
    originalPrice: 1299,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Travel Mugs',
    bulkPricing: [
      { minQty: 25, price: 1049 },
      { minQty: 50, price: 999 },
      { minQty: 100, price: 949 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#ffffff', '#1e3a5f'],
    inStock: true,
    stock: 320,
    rating: 4.8,
    reviews: 156,
    badge: 'new',
  },
  {
    id: 'XG-M23',
    sku: 'XG-M23',
    name: 'Double Wall Stainless Steel Mug with Cork Base',
    description: 'Premium mug with cork base for stability and spill-proof lid.',
    keyComponents: 'Stainless steel mug with cork base',
    materials: 'Double Wall Stainless Steel, Cork',
    specifications: '450 ml, 170 mm × 95 mm, 320g',
    designFeatures: 'Cork base, spill-proof lid',
    price: 849,
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    category: 'mugs',
    subcategory: 'Insulated Mugs',
    bulkPricing: [
      { minQty: 25, price: 799 },
      { minQty: 50, price: 749 },
      { minQty: 100, price: 699 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 380,
    rating: 4.7,
    reviews: 178,
  },

  // =================== WATER BOTTLES ===================
  {
    id: 'XG-002',
    sku: 'XG-002',
    name: 'Vacuum-Insulated 304 Stainless Steel Bottle with Wrist Strap',
    description: 'Premium vacuum insulated bottle with secure cap and wrist strap. Stylish design for professionals.',
    keyComponents: 'Secure cap and wrist strap',
    materials: '304 Stainless Steel',
    specifications: '750 ml, 22 cm × 6.6 cm, 500g',
    designFeatures: 'Stylish, vacuum insulated, secure strap',
    price: 699,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Vacuum Insulated',
    bulkPricing: [
      { minQty: 25, price: 649 },
      { minQty: 50, price: 599 },
      { minQty: 100, price: 549 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#2d2d2d', '#ffffff', '#dc2626'],
    inStock: true,
    stock: 700,
    rating: 4.8,
    reviews: 456,
    badge: 'bestseller',
  },
  {
    id: 'XG-004',
    sku: 'XG-004',
    name: 'Lightweight Aluminum 304 Stainless Steel Bottle with Carabiner',
    description: 'Lightweight bottle with carabiner clip for easy carrying. Perfect for outdoor activities.',
    keyComponents: 'Carabiner clip for easy carrying',
    materials: 'Aluminum 304 Stainless Steel',
    specifications: '750 ml, 23.6 cm × 7.3 cm, 400g',
    designFeatures: 'Lightweight, carabiner clip',
    price: 649,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Aluminum Bottles',
    bulkPricing: [
      { minQty: 25, price: 599 },
      { minQty: 50, price: 549 },
      { minQty: 100, price: 499 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#dc2626', '#22c55e'],
    inStock: true,
    stock: 550,
    rating: 4.6,
    reviews: 312,
  },
  {
    id: 'XG-008',
    sku: 'XG-008-bottle',
    name: 'Lightweight Aluminum Metal Bottle with Silicon Strap Cap',
    description: 'Durable aluminum bottle with silicon strap cap. Sleek and portable.',
    keyComponents: 'Durable silicon strap cap',
    materials: 'Aluminum Metal',
    specifications: '750 ml, 23 cm × 6.6 cm, 300g',
    designFeatures: 'Silicon strap cap, sleek design',
    price: 549,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Aluminum Bottles',
    bulkPricing: [
      { minQty: 25, price: 499 },
      { minQty: 50, price: 449 },
      { minQty: 100, price: 399 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 600,
    rating: 4.5,
    reviews: 267,
  },
  {
    id: 'XG-009',
    sku: 'XG-009',
    name: 'Premium Stainless Steel Bottle with Flip-Top Lid',
    description: 'High-grade stainless steel bottle with flip-top lid and ergonomic grip.',
    keyComponents: 'Flip-top lid, ergonomic grip',
    materials: 'High-Grade Stainless Steel',
    specifications: '750 ml, 24.5 cm × 7 cm, 300g',
    designFeatures: 'Flip-top lid, ergonomic grip',
    price: 699,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Stainless Steel',
    bulkPricing: [
      { minQty: 25, price: 649 },
      { minQty: 50, price: 599 },
      { minQty: 100, price: 549 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#dc2626', '#ffffff'],
    inStock: true,
    stock: 480,
    rating: 4.7,
    reviews: 345,
    badge: 'new',
  },
  {
    id: 'XG-011-bottle',
    sku: 'XG-011-bottle',
    name: 'Single-Wall Stainless Steel Bottle with Leak-Proof Cap',
    description: 'Premium single-wall bottle with leak-proof cap. Keeps drinks cold 12hrs, hot 6hrs.',
    keyComponents: 'Leak-proof cap, sleek design',
    materials: '18/8 Stainless Steel',
    specifications: '750 ml, 31.5 cm × 8 cm, 250g',
    designFeatures: 'Leak-proof, sweat-free, BPA-free, 12H cold/6H hot',
    price: 599,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Stainless Steel',
    bulkPricing: [
      { minQty: 25, price: 549 },
      { minQty: 50, price: 499 },
      { minQty: 100, price: 449 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff', '#f97316'],
    inStock: true,
    stock: 520,
    rating: 4.6,
    reviews: 289,
  },
  {
    id: 'XG-015-bottle',
    sku: 'XG-015',
    name: 'Ergonomic 304 Stainless Steel Bottle with Flip-Top Sipper',
    description: 'Anti-slip grip coating with flip-top sipper lid. Complete protection features.',
    keyComponents: 'Flip-top sipper lid, anti-slip grip',
    materials: '304 Stainless Steel',
    specifications: '750 ml, 22.5 cm × 7.2 cm, 250g',
    designFeatures: 'Anti-fingerprints, easy grip, scratch defense, condensation proof',
    price: 749,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Sports Bottles',
    bulkPricing: [
      { minQty: 25, price: 699 },
      { minQty: 50, price: 649 },
      { minQty: 100, price: 599 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#dc2626'],
    inStock: true,
    stock: 420,
    rating: 4.8,
    reviews: 234,
    badge: 'bestseller',
  },
  {
    id: 'XG-017',
    sku: 'XG-017',
    name: 'Classic 304 Vacuum-Insulated Bottle with Steel Cap',
    description: 'Brushed finish vacuum-insulated bottle with leak-proof steel cap.',
    keyComponents: 'Brushed finish, leak-proof steel cap',
    materials: '304 Stainless Steel',
    specifications: '1000 ml, 28.3 cm × 7.3 cm, 500g',
    designFeatures: 'Vacuum insulated, brushed finish',
    price: 899,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Vacuum Insulated',
    bulkPricing: [
      { minQty: 25, price: 849 },
      { minQty: 50, price: 799 },
      { minQty: 100, price: 749 },
    ],
    customizable: true,
    colors: ['#c0c0c0', '#2d2d2d', '#1e3a5f'],
    inStock: true,
    stock: 380,
    rating: 4.7,
    reviews: 198,
  },
  {
    id: 'XG-030',
    sku: 'XG-030',
    name: 'Eco-Friendly Water Bottle with Bamboo Lid',
    description: 'Sleek insulated bottle with modern bamboo lid. Keeps hot 12hrs, cold 24hrs.',
    keyComponents: 'Bamboo lid, insulated body',
    materials: 'Stainless Steel, Bamboo',
    specifications: '500 ml, 18 cm × 22.5 cm × 7.5 cm, 280g',
    designFeatures: 'Eco-friendly, 12H hot/24H cold',
    price: 849,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Bamboo Lid',
    bulkPricing: [
      { minQty: 25, price: 799 },
      { minQty: 50, price: 749 },
      { minQty: 100, price: 699 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d', '#ffffff'],
    inStock: true,
    stock: 350,
    rating: 4.9,
    reviews: 178,
    badge: 'new',
  },
  {
    id: 'XG-031',
    sku: 'XG-031',
    name: 'Vacuum Insulated 304 Bottle with Matte Finish',
    description: '100% leak-proof bottle with double-layer insulation. Anti-slip cup bottom design.',
    keyComponents: 'Leak-proof cap, anti-slip bottom',
    materials: '304 Stainless Steel',
    specifications: '500 ml, 22.5 cm × 7 cm, 188g',
    designFeatures: '100% leakproof, 360° shake-proof, BPA-free, reusable',
    price: 699,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80',
    category: 'water-bottles',
    subcategory: 'Vacuum Insulated',
    bulkPricing: [
      { minQty: 25, price: 649 },
      { minQty: 50, price: 599 },
      { minQty: 100, price: 549 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff', '#dc2626'],
    inStock: true,
    stock: 450,
    rating: 4.6,
    reviews: 267,
  },

  // =================== KEYCHAINS ===================
  {
    id: 'XG-K1',
    sku: 'XG-K1',
    name: 'Circular Shaped Stainless Steel Keychain',
    description: 'Gloss finish circular stainless steel keychain. Perfect for engraving or print branding.',
    keyComponents: 'Circular stainless steel keychain',
    materials: 'Stainless Steel',
    specifications: 'Gloss finish, Silver color',
    designFeatures: 'Engraving / Print branding, pp Packing',
    price: 99,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Metal Keychains',
    bulkPricing: [
      { minQty: 50, price: 89 },
      { minQty: 100, price: 79 },
      { minQty: 250, price: 69 },
    ],
    customizable: true,
    colors: ['#c0c0c0'],
    inStock: true,
    stock: 2000,
    rating: 4.4,
    reviews: 567,
  },
  {
    id: 'XG-K2',
    sku: 'XG-K2',
    name: 'Rounded Edge Rectangular Keychain',
    description: 'Matt finish stainless steel keychain with rounded edges.',
    keyComponents: 'Rectangular stainless steel keychain',
    materials: 'Stainless Steel',
    specifications: 'Matt finish, 18.4g',
    designFeatures: 'Rounded edges, engraving / print branding',
    price: 109,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Metal Keychains',
    bulkPricing: [
      { minQty: 50, price: 99 },
      { minQty: 100, price: 89 },
      { minQty: 250, price: 79 },
    ],
    customizable: true,
    colors: ['#c0c0c0'],
    inStock: true,
    stock: 1800,
    rating: 4.5,
    reviews: 423,
  },
  {
    id: 'XG-K3',
    sku: 'XG-K3',
    name: '3-in-1 Keychain with Bottle Opener',
    description: 'Multi-function keychain: Key holder, loop, and bottle opener in one.',
    keyComponents: 'Key holder, Loop, Bottle opener',
    materials: 'Stainless Steel',
    specifications: '10 cm H × 3.3 cm W, 0.8 cm thick, 36g',
    designFeatures: 'Multi-function, engraving / print branding',
    price: 149,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Multi-function Keychains',
    bulkPricing: [
      { minQty: 50, price: 139 },
      { minQty: 100, price: 129 },
      { minQty: 250, price: 119 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513'],
    inStock: true,
    stock: 1500,
    rating: 4.7,
    reviews: 312,
    badge: 'bestseller',
  },
  {
    id: 'XG-K4',
    sku: 'K4',
    name: 'House Shaped Keychain',
    description: 'Metallic black house-shaped keychain. Perfect for real estate branding.',
    keyComponents: 'House-shaped metal keychain',
    materials: 'Metal',
    specifications: '44mm, Metallic Black',
    designFeatures: 'Laser / Screen / UV branding',
    price: 89,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Metal Keychains',
    bulkPricing: [
      { minQty: 100, price: 79 },
      { minQty: 250, price: 69 },
      { minQty: 500, price: 59 },
    ],
    customizable: true,
    colors: ['#2d2d2d'],
    inStock: true,
    stock: 2500,
    rating: 4.3,
    reviews: 234,
  },
  {
    id: 'K-20',
    sku: 'K-20',
    name: 'Bamboo With Stainless Steel Keychain',
    description: 'Eco-friendly bamboo and stainless steel keychain. Natural bamboo finish.',
    keyComponents: 'Bamboo and steel keychain',
    materials: 'Bamboo, Stainless Steel',
    specifications: 'Natural Bamboo color',
    designFeatures: 'UV Print, Laser & Screen branding',
    price: 129,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Bamboo Keychains',
    bulkPricing: [
      { minQty: 50, price: 119 },
      { minQty: 100, price: 109 },
      { minQty: 250, price: 99 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 1200,
    rating: 4.6,
    reviews: 234,
    badge: 'new',
  },
  {
    id: 'K-25',
    sku: 'K-25',
    name: 'PU Leather With Metal Keychain',
    description: 'Premium PU leather keychain with metal frame. Multiple color options.',
    keyComponents: 'PU leather with metal frame',
    materials: 'PU Leather, Metal',
    specifications: 'Blue, Black, Red, Grey options',
    designFeatures: 'UV Print, Laser & Screen branding',
    price: 159,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Leather Keychains',
    bulkPricing: [
      { minQty: 50, price: 149 },
      { minQty: 100, price: 139 },
      { minQty: 250, price: 129 },
    ],
    customizable: true,
    colors: ['#1e3a5f', '#2d2d2d', '#dc2626', '#6b7280'],
    inStock: true,
    stock: 900,
    rating: 4.5,
    reviews: 178,
  },
  {
    id: 'XG-K31',
    sku: 'XG-K31',
    name: 'Round Bamboo Wooden & Metal Keychain',
    description: 'Premium metal frame with polished finish encasing natural wooden inlay. Classic round design.',
    keyComponents: 'Metal frame with wooden inlay',
    materials: 'Metal, Natural Wood',
    specifications: 'Round design with visible wood grain',
    designFeatures: 'Robust metal split ring, ideal for custom engraving',
    price: 139,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Wooden Keychains',
    bulkPricing: [
      { minQty: 50, price: 129 },
      { minQty: 100, price: 119 },
      { minQty: 250, price: 109 },
    ],
    customizable: true,
    colors: ['#8B4513', '#c0c0c0'],
    inStock: true,
    stock: 1000,
    rating: 4.6,
    reviews: 189,
  },
  {
    id: 'XG-K36',
    sku: 'XG-K36',
    name: 'Modern Metal & Leather Hook Keychain',
    description: 'Contemporary metal top with secure hook/clip closure. Stylish black faux leather strap.',
    keyComponents: 'Metal hook with faux leather strap',
    materials: 'Metal, Faux Leather',
    specifications: 'Rectangular metal top, black faux leather strap',
    designFeatures: 'Modern aesthetic, versatile attachment',
    price: 179,
    image: 'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80',
    category: 'keychains',
    subcategory: 'Leather Keychains',
    bulkPricing: [
      { minQty: 50, price: 169 },
      { minQty: 100, price: 159 },
      { minQty: 250, price: 149 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513'],
    inStock: true,
    stock: 800,
    rating: 4.5,
    reviews: 156,
  },

  // =================== DESKTOP ORGANIZERS ===================
  {
    id: 'XG-D01',
    sku: 'XG-D01',
    name: 'Study Room Desk Table Clock Organizer',
    description: 'Complete desk organizer with clock, pen holder, mobile slot, and customizable calendar.',
    keyComponents: 'Clock, pen holder, mobile slot, perpetual calendar',
    materials: 'Premium MDF Wood',
    specifications: '8 inches × 2.5 inches, 3.5 inch folding watch',
    designFeatures: 'Removable clock, customizable name plate, never-ending calendar',
    price: 899,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Wooden Organizers',
    bulkPricing: [
      { minQty: 25, price: 849 },
      { minQty: 50, price: 799 },
      { minQty: 100, price: 749 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 400,
    rating: 4.8,
    reviews: 267,
    badge: 'bestseller',
  },
  {
    id: 'XG-D02',
    sku: 'XG-D02',
    name: 'Multi-Function Organizer Pen Stand with Clock',
    description: 'All-in-one desk organizer with analog clock and pen/mobile holders.',
    keyComponents: 'Analog clock, pen holder, mobile holder',
    materials: 'Premium MDF Wood',
    specifications: '27 cm × 7 cm',
    designFeatures: 'Built-in analog clock, removable clock design, customizable name plate',
    price: 999,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Multi-function Organizers',
    bulkPricing: [
      { minQty: 25, price: 949 },
      { minQty: 50, price: 899 },
      { minQty: 100, price: 849 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 350,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 'XG-D03',
    sku: 'XG-D03',
    name: 'Wooden Desk Organizer with Clock & Mobile Holder',
    description: 'Premium solid beech wood organizer with folding watch, pen & phone holder.',
    keyComponents: 'Folding watch, pen holder, phone holder',
    materials: 'Solid Beech Wood',
    specifications: '18.8 cm × 6.7 cm × 10 cm',
    designFeatures: 'Built-in analog clock, removable clock, customizable name engraving',
    price: 1099,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Desk Clocks',
    bulkPricing: [
      { minQty: 25, price: 1049 },
      { minQty: 50, price: 999 },
      { minQty: 100, price: 949 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 280,
    rating: 4.9,
    reviews: 178,
    badge: 'new',
  },
  {
    id: 'XG-D06',
    sku: 'XG-D06',
    name: 'Apple Clock Desk Organizer with Phone & Pen Holder',
    description: 'Unique apple-shaped clock design with visiting card slot, pen holder, and mobile holder.',
    keyComponents: 'Apple clock, pen holder, mobile holder, visiting card slot',
    materials: 'Durable MDF Wood',
    specifications: '19 cm × 7 cm × 6.5 cm',
    designFeatures: 'Apple clock design, removable clock, customizable name engraving',
    price: 849,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'MDF Organizers',
    bulkPricing: [
      { minQty: 25, price: 799 },
      { minQty: 50, price: 749 },
      { minQty: 100, price: 699 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513'],
    inStock: true,
    stock: 320,
    rating: 4.6,
    reviews: 145,
  },
  {
    id: 'XG-D08',
    sku: 'XG-D08',
    name: 'Multi-Purpose Desk Organizer with Rotating Calendar',
    description: 'Complete organizer with rotating perpetual calendar, compact calendar insert, and dual-side date panels.',
    keyComponents: 'Rotating calendar, pen holder, mobile holder',
    materials: 'Black MDF Wood',
    specifications: '20 cm × 6 cm × 10.5 cm',
    designFeatures: 'Rotating perpetual calendar, easy-to-read dual date panels',
    price: 799,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Multi-function Organizers',
    bulkPricing: [
      { minQty: 25, price: 749 },
      { minQty: 50, price: 699 },
      { minQty: 100, price: 649 },
    ],
    customizable: true,
    colors: ['#2d2d2d'],
    inStock: true,
    stock: 380,
    rating: 4.5,
    reviews: 167,
  },
  {
    id: 'XG-D09',
    sku: 'XG-D09',
    name: 'Wooden Desk Organizer with Pen Holder & Mobile Stand',
    description: 'Natural wood organizer with sections for pens, visiting cards, and phone.',
    keyComponents: 'Pen holder, visiting card slot, mobile stand',
    materials: 'Premium Natural Wood',
    specifications: '18 cm × 6 cm × 9 cm',
    designFeatures: 'Space-saving compact design, elegant professional look',
    price: 749,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Wooden Organizers',
    bulkPricing: [
      { minQty: 25, price: 699 },
      { minQty: 50, price: 649 },
      { minQty: 100, price: 599 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 400,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 'XG-D10',
    sku: 'XG-D10',
    name: 'Premium Wooden Clock Pen Stand',
    description: 'Elegant solid wood pen stand with built-in clock. Unique folding design.',
    keyComponents: 'Built-in pen holder, clock access slot',
    materials: 'High-Quality Beech Wood',
    specifications: '2.5 inch clock',
    designFeatures: 'Compact & modern, unique folding design, customizable engraving',
    price: 899,
    originalPrice: 1099,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    category: 'desktop-organizers',
    subcategory: 'Pen Holders',
    bulkPricing: [
      { minQty: 25, price: 849 },
      { minQty: 50, price: 799 },
      { minQty: 100, price: 749 },
    ],
    customizable: true,
    colors: ['#8B4513'],
    inStock: true,
    stock: 250,
    rating: 4.8,
    reviews: 156,
    badge: 'new',
  },

  // =================== NOTEBOOKS & DIARIES ===================
  {
    id: 'XG-NB01',
    sku: 'XG-NB01',
    name: 'A5 PU Leather Executive Notebook with Magnetic Buckle',
    description: 'Premium executive notebook with magnetic clasp and pen holder. 200 ruled pages.',
    keyComponents: 'Magnetic clasp, pen holder',
    materials: 'PU Vegan Leather',
    specifications: '148 mm × 212 mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Magnetic buckle closure, pen holder, hardcover',
    price: 499,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'A5 Notebooks',
    bulkPricing: [
      { minQty: 50, price: 449 },
      { minQty: 100, price: 399 },
      { minQty: 250, price: 349 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513', '#1e3a5f', '#dc2626'],
    inStock: true,
    stock: 800,
    rating: 4.9,
    reviews: 456,
    badge: 'bestseller',
  },
  {
    id: 'XG-NB02',
    sku: 'XG-NB02',
    name: 'Premium PU Leather Business Diary with Geometric Flap',
    description: 'Stylish business diary with geometric flap closure. Professional look.',
    keyComponents: 'Geometric flap closure',
    materials: 'PU Vegan Leather',
    specifications: '148 mm × 210 mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Magnetic clasp, geometric design, hardcover',
    price: 549,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'Executive Diaries',
    bulkPricing: [
      { minQty: 50, price: 499 },
      { minQty: 100, price: 449 },
      { minQty: 250, price: 399 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#8B4513'],
    inStock: true,
    stock: 650,
    rating: 4.8,
    reviews: 312,
  },
  {
    id: 'XG-NB04',
    sku: 'XG-NB04',
    name: 'Eco-Smart Bamboo Closure Notebook with Phone Holder',
    description: 'Innovative notebook with elastic strap, bamboo closure, and phone holder slot.',
    keyComponents: 'Elastic band, bamboo closure, pen loop, phone holder',
    materials: 'PU Vegan Leather, Bamboo',
    specifications: '148 mm × 210 mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Eco-friendly bamboo closure, phone holder',
    price: 599,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'Bamboo Notebooks',
    bulkPricing: [
      { minQty: 50, price: 549 },
      { minQty: 100, price: 499 },
      { minQty: 250, price: 449 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d'],
    inStock: true,
    stock: 500,
    rating: 4.7,
    reviews: 234,
    badge: 'new',
  },
  {
    id: 'XG-NB07',
    sku: 'XG-NB07',
    name: 'Premium Leather-Bound Notebook with Metallic Clasp & Card Slots',
    description: 'Executive notebook with metallic clasp and built-in card slots for business cards.',
    keyComponents: 'Metallic clasp, card slots',
    materials: 'PU Vegan Leather',
    specifications: '148 mm × 210 mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Card slots for business cards, credit cards, or ID',
    price: 649,
    originalPrice: 749,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'Executive Diaries',
    bulkPricing: [
      { minQty: 50, price: 599 },
      { minQty: 100, price: 549 },
      { minQty: 250, price: 499 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513', '#1e3a5f'],
    inStock: true,
    stock: 420,
    rating: 4.8,
    reviews: 198,
    badge: 'bestseller',
  },
  {
    id: 'XG-NB16',
    sku: 'XG-NB16',
    name: 'Premium PU Leather Notebook with Elastic Closure & Back Pocket',
    description: 'Versatile notebook with elastic closure and convenient back pocket storage.',
    keyComponents: 'Elastic closure, bookmark, back pocket',
    materials: 'PU Vegan Leather',
    specifications: '148 mm × 212 mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Back pocket storage space, bookmark',
    price: 549,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'A5 Notebooks',
    bulkPricing: [
      { minQty: 50, price: 499 },
      { minQty: 100, price: 449 },
      { minQty: 250, price: 399 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#dc2626', '#8B4513'],
    inStock: true,
    stock: 550,
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 'XG-NB20',
    sku: 'XG-NB20',
    name: 'PU Leather Executive Ring Binder Notebook',
    description: 'Refillable ring binder notebook with magnetic snap closure and metal rings.',
    keyComponents: 'Metal binder rings, magnetic snap closure, pen loop',
    materials: 'Soft PU Vegan Leather',
    specifications: '148 mm × 212 mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Ring binder (refillable), bend without crease',
    price: 699,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'Executive Diaries',
    bulkPricing: [
      { minQty: 50, price: 649 },
      { minQty: 100, price: 599 },
      { minQty: 250, price: 549 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#8B4513', '#1e3a5f'],
    inStock: true,
    stock: 380,
    rating: 4.7,
    reviews: 178,
  },
  {
    id: 'XG-NB21',
    sku: 'XG-NB21',
    name: 'PU Leather Executive Notebook with Geometric Pocket',
    description: 'Stylish notebook with geometric pocket design and card slots.',
    keyComponents: 'Geometric pocket, card slots, pen loop',
    materials: 'PU Vegan Leather',
    specifications: '148 mm × 212 mm, 200 pages, 80 GSM, 450g',
    designFeatures: 'Card slots for business cards, geometric pocket design',
    price: 599,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    category: 'notebooks',
    subcategory: 'A5 Notebooks',
    bulkPricing: [
      { minQty: 50, price: 549 },
      { minQty: 100, price: 499 },
      { minQty: 250, price: 449 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#8B4513'],
    inStock: true,
    stock: 450,
    rating: 4.8,
    reviews: 189,
    badge: 'new',
  },

  // =================== ELECTRONICS ===================
  {
    id: 'XG-T01',
    sku: 'XG-T01',
    name: '10000mAh Power Bank with LED Display',
    description: 'Compact power bank with LED battery indicator. Dual USB ports and Type-C input for fast charging.',
    keyComponents: 'LED battery indicator, Dual USB ports',
    materials: 'ABS Plastic, Lithium Battery',
    specifications: '10000mAh, Type-C input',
    designFeatures: 'Compact, fast charging, dual ports',
    price: 999,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80',
    category: 'electronics',
    subcategory: 'Power Banks',
    bulkPricing: [
      { minQty: 25, price: 899 },
      { minQty: 50, price: 799 },
      { minQty: 100, price: 699 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#ffffff', '#1e3a5f'],
    inStock: true,
    stock: 400,
    rating: 4.6,
    reviews: 312,
    badge: 'bestseller',
  },
  {
    id: 'XG-T11',
    sku: 'XG-T11',
    name: 'Fusion Multi-Function Wireless Sound Box',
    description: 'Bluetooth speaker with clock, phone stand, and pen holder. All-in-one desk accessory.',
    keyComponents: 'Bluetooth speaker, Clock, Phone stand, Pen holder',
    materials: 'ABS Plastic, Metal',
    specifications: 'Bluetooth v5.3, 5W speaker, 1200mAh battery, 4-8hr play',
    designFeatures: 'Telescopic phone holder, Pen stand, Alarm, Temperature display',
    price: 1499,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    category: 'electronics',
    subcategory: 'Speakers',
    bulkPricing: [
      { minQty: 25, price: 1399 },
      { minQty: 50, price: 1299 },
      { minQty: 100, price: 1199 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#ffffff'],
    inStock: true,
    stock: 300,
    rating: 4.7,
    reviews: 198,
    badge: 'new',
  },
  {
    id: 'XG-T62',
    sku: 'XG-T62',
    name: 'Wireless Sport Earphone',
    description: 'Wireless over-ear sports earphones with up to 16hrs playtime. Cool lighting and protein leather ear muffs.',
    keyComponents: 'Wireless over-ear sports earphones',
    materials: 'Protein Leather, ABS Plastic',
    specifications: 'Up to 16hrs playtime, CVC microphone',
    designFeatures: 'Cool lighting, Protein leather ear muffs, Folding design, Ergonomic',
    price: 1799,
    originalPrice: 2199,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80',
    category: 'electronics',
    subcategory: 'Earbuds',
    bulkPricing: [
      { minQty: 25, price: 1699 },
      { minQty: 50, price: 1599 },
      { minQty: 100, price: 1499 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#ffffff'],
    inStock: true,
    stock: 350,
    rating: 4.5,
    reviews: 145,
    badge: 'sale',
  },

  // =================== ACCESSORIES ===================
  {
    id: 'XG-Y09',
    sku: 'XG-Y09',
    name: 'Oval Shaped Retractable Loop Badge Holder',
    description: 'Professional retractable badge holder with oval shape and loop design. Secure and durable.',
    keyComponents: 'Retractable loop, oval shape',
    materials: 'Plastic, Metal',
    specifications: '65 mm × 10 mm',
    designFeatures: 'Retractable, secure, professional',
    price: 79,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'accessories',
    subcategory: 'Badge Holders',
    bulkPricing: [
      { minQty: 50, price: 69 },
      { minQty: 100, price: 59 },
      { minQty: 250, price: 49 },
    ],
    customizable: true,
    colors: ['#2d2d2d', '#1e3a5f', '#dc2626'],
    inStock: true,
    stock: 3000,
    rating: 4.3,
    reviews: 567,
  },
  {
    id: 'XG-GS-254',
    sku: 'XG-GS-254',
    name: '3-in-1 Leather Card Holder Set',
    description: 'Premium brown leather card holder with keychain and metal pen. Multi-function set.',
    keyComponents: 'Leather card holder, Keychain, Metal pen',
    materials: 'Brown Leather, Metal',
    specifications: 'Compact gift set',
    designFeatures: 'Multi-function keychain (bottle opener, loop)',
    price: 699,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'accessories',
    subcategory: 'Card Holders',
    bulkPricing: [
      { minQty: 25, price: 649 },
      { minQty: 50, price: 599 },
      { minQty: 100, price: 549 },
    ],
    customizable: true,
    colors: ['#8B4513', '#2d2d2d', '#ffffff'],
    inStock: true,
    stock: 400,
    rating: 4.6,
    reviews: 234,
  },
];

export const businessNeeds = [
  {
    id: 'startups',
    title: 'For Startups',
    description: 'Budget-friendly branded merchandise',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&q=80',
  },
  {
    id: 'corporate',
    title: 'Corporate Gifts',
    description: 'Premium gifts for clients & partners',
    image: 'https://images.unsplash.com/photo-1513001900722-370f803f498d?w=400&q=80',
  },
  {
    id: 'events',
    title: 'Event Merchandise',
    description: 'Branded swag for conferences & events',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&q=80',
  },
  {
    id: 'employee',
    title: 'Employee Kits',
    description: 'Welcome kits & appreciation gifts',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&q=80',
  },
];
